apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nxa3j6vgp-nodejs 
  janus-idp.io/tekton: nxa3j6vgp-nodejs
  backstage.io/kubernetes-id: nxa3j6vgp-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nxa3j6vgp-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml